### ISSUE TITLE
EPIC: Favoritar Materiais

### ISSUE THREAD

**Issue by rluders** [sumeedu/bancodeitinerarios#5]
**História de usuário**

- Como um **usuário logado no sistema**
- Eu quero **favoritar materiais e itinerários formativos**
- Para que **visualizar eles mais facilmente na minha lista de favoritos**

**Como seria a sua solução?**

- Por meio de um botão o usuário pode adicionar um material em sua lista de favoritos;
- O botão deverá indicar visualmente que o material foi adicionado aos favoritos;
- Ao clicar sobre o botão que indica que o material já está favoritado ele deve remover o item da lista de favoritos;

**Tarefas**

- [ ] Implementar backend para adicionar e remover materiais a lista de favoritos
- [ ] Integrar ação de favoritar e desfavoritar com frontend
- [ ] Implementar página de listagem de favoritos

**Informações adicionais**
n/a
